services:
  # A Flask web service
  - type: web
    name: otpservice-app
    runtime: python
    plan: free
    buildCommand: pip install -r render_requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: otpservice-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: otpservice-db
    plan: free
    ipAllowList: [] # No IP restrictions